openapi: "3.0.2"
info:
  title: Transaction API
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /transactions:
    get:
      operationId: get-all-transactions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionDto'
    post:
      operationId: create-transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDto'

  /transactions/{id}:
    put:
      operationId: update-transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDto'

components:
  schemas:
    TransactionDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        timestamp:
          type: string
          format: date-time
        data:
          type: string
        reference:
          type: string
        amount:
          type: integer